### ISSUE TITLE
Posição inicial dos estímulos

### ISSUE THREAD

**Issue by cpicanco** [eep-lab/arrasta#27]
Olha só:

https://github.com/eep-lab/arrasta/blob/d5b64418ee90959e06d4811fd3e200b49bcd5a8f/src/units/stimuli.image.base.pas#L330-L340

Que tal criar uma função para retornar essa variável?

**Comment by fellipecastro7** [comment]
No caso, esses parâmetros se referem aos limites do quadrado, certo?
